version: '3.8'

networks:
  psql-network:

services:
  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - './.env'
    restart: always
    networks:
      - psql-network

  reservenow-back:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - psql-network

  migration:
    build:
      context: .
    command:
      [
        './wait-for-it/wait-for-it.sh',
        '-t',
        '30',
        'postgres:${POSTGRES_PORT}',
        '--',
        './wait-for-it/wait-for-it.sh',
        'reservenow-back:${SERVER_PORT}',
        '--',
        'npm',
        'run',
        'migration:run',
      ]
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - psql-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_CONTAINER_PORT}'
    networks:
      - psql-network
